# Generated by Django 3.0.5 on 2020-11-30 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('puname', models.CharField(max_length=255)),
                ('padd', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('startdate', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('createdate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('puname', models.CharField(max_length=255)),
                ('padd', models.CharField(max_length=255)),
                ('medicineprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('psw', models.CharField(max_length=150)),
                ('utype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailadd', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(max_length=255)),
                ('puname', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('add', models.CharField(max_length=255)),
                ('sup', models.CharField(max_length=255)),
                ('medquantity', models.IntegerField()),
                ('medprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(max_length=255)),
                ('puname', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('add', models.CharField(max_length=255)),
                ('sup', models.CharField(max_length=255)),
                ('medquantity', models.IntegerField()),
                ('medprice', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('expdate', models.CharField(max_length=255)),
                ('reqtype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacySignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('oname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=150)),
                ('utype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('puname', models.CharField(max_length=255)),
                ('padd', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('startdate', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('createdate', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('puname', models.CharField(max_length=100)),
                ('padd', models.CharField(max_length=100)),
                ('cname', models.EmailField(max_length=254)),
                ('mname', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('datetime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('utype', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
